/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/gpio.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/gpio.h>

/* TODO(ameba): implement — nn_osal/gpio.h */
nn_osal_gpio_pin_t * nn_osal_gpio_get(const char *logical_name)
{
    return NULL;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_register(const char *logical_name, nn_osal_gpio_pin_t *pin)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_from_raw(nn_osal_gpio_pin_t *pin, nn_osal_gpio_port_t *port, uint32_t pin_number, uint32_t flags)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_configure(nn_osal_gpio_pin_t *pin, uint32_t flags)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_get_logical(const nn_osal_gpio_pin_t *pin)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_set_logical(nn_osal_gpio_pin_t *pin, int value)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_toggle(nn_osal_gpio_pin_t *pin)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
bool nn_osal_gpio_port_ready(nn_osal_gpio_port_t *port)
{
    return false;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
void nn_osal_gpio_callback_init(nn_osal_gpio_callback_t *cb, nn_osal_gpio_cb_t handler, uint32_t pin_mask)
{
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_add_callback(nn_osal_gpio_pin_t *pin, nn_osal_gpio_callback_t *cb)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/gpio.h */
int nn_osal_gpio_interrupt_configure(nn_osal_gpio_pin_t *pin, uint32_t flags)
{
    return -ENOTSUP;
}
