/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/shell.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/shell.h>

/* TODO(ameba): implement — nn_osal/shell.h */
void nn_osal_shell_print(nn_osal_shell_ctx_t *sh, const char *fmt, ...)
{
}

/* TODO(ameba): implement — nn_osal/shell.h */
void nn_osal_shell_error(nn_osal_shell_ctx_t *sh, const char *fmt, ...)
{
}

/* TODO(ameba): implement — nn_osal/shell.h */
void nn_osal_shell_warn(nn_osal_shell_ctx_t *sh, const char *fmt, ...)
{
}

/* TODO(ameba): implement — nn_osal/shell.h */
void nn_osal_shell_print_v(nn_osal_shell_ctx_t *sh, const char *fmt, va_list ap)
{
}
