/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/socket.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/socket.h>

/* TODO(ameba): implement — nn_osal/socket.h */
nn_osal_socket_t nn_osal_socket(int domain, int type, int protocol)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_close(nn_osal_socket_t sock)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_bind(nn_osal_socket_t sock, const nn_osal_sockaddr_in6_t *addr)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_connect(nn_osal_socket_t sock, const nn_osal_sockaddr_in6_t *addr)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_listen(nn_osal_socket_t sock, int backlog)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
nn_osal_socket_t nn_osal_accept(nn_osal_socket_t sock, nn_osal_sockaddr_in6_t *peer)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_send(nn_osal_socket_t sock, const void *buf, size_t len, int flags)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_sendto(nn_osal_socket_t sock, const void *buf, size_t len, int flags, const nn_osal_sockaddr_in6_t *dst)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_recv(nn_osal_socket_t sock, void *buf, size_t len, int flags)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_recvfrom(nn_osal_socket_t sock, void *buf, size_t len, int flags, nn_osal_sockaddr_in6_t *src)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_setsockopt(nn_osal_socket_t sock, int level, int optname, const void *optval, size_t optlen)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_poll(nn_osal_pollfd_t *fds, size_t nfds, int timeout_ms)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_inet_pton6(const char *str, uint8_t out_addr[16])
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/socket.h */
int nn_osal_inet_ntop6(const uint8_t addr[16], char *out, size_t out_cap)
{
    return -ENOTSUP;
}
