/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/storage.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/storage.h>

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_kv_init(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_kv_register(const char *prefix, nn_osal_kv_load_cb cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_kv_load_all(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_kv_save(const char *key, const void *data, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_kv_delete(const char *key)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
nn_osal_dfu_ctx_t * nn_osal_dfu_ctx_alloc(void)
{
    return NULL;
}

/* TODO(ameba): implement — nn_osal/storage.h */
void nn_osal_dfu_ctx_free(nn_osal_dfu_ctx_t *ctx)
{
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_dfu_begin(nn_osal_dfu_ctx_t *ctx, size_t expected_size)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_dfu_write(nn_osal_dfu_ctx_t *ctx, const uint8_t *buf, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_dfu_finalise(nn_osal_dfu_ctx_t *ctx)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_dfu_request_upgrade(bool permanent)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/storage.h */
int nn_osal_dfu_confirm(void)
{
    return -ENOTSUP;
}
