/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/sync.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/sync.h>

/* TODO(ameba): implement — nn_osal/sync.h */
int nn_osal_sem_init(nn_osal_sem_t *sem, unsigned initial_count, unsigned max_count)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/sync.h */
int nn_osal_sem_take(nn_osal_sem_t *sem, int timeout_ms)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/sync.h */
void nn_osal_sem_give(nn_osal_sem_t *sem)
{
}

/* TODO(ameba): implement — nn_osal/sync.h */
void nn_osal_sem_reset(nn_osal_sem_t *sem)
{
}

/* TODO(ameba): implement — nn_osal/sync.h */
unsigned nn_osal_sem_count_get(const nn_osal_sem_t *sem)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/sync.h */
int nn_osal_mutex_init(nn_osal_mutex_t *mtx)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/sync.h */
int nn_osal_mutex_lock(nn_osal_mutex_t *mtx, int timeout_ms)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/sync.h */
void nn_osal_mutex_unlock(nn_osal_mutex_t *mtx)
{
}
