/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/thread.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/thread.h>

/* TODO(ameba): implement — nn_osal/thread.h */
int nn_osal_thread_create(nn_osal_thread_t *thread, void *stack, size_t stack_size, nn_osal_thread_entry_t entry, void *arg1, void *arg2, void *arg3, int prio, const char *name)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/thread.h */
void nn_osal_thread_yield(void)
{
}

/* TODO(ameba): implement — nn_osal/thread.h */
void nn_osal_thread_suspend(nn_osal_thread_t *thread)
{
}

/* TODO(ameba): implement — nn_osal/thread.h */
void nn_osal_thread_resume(nn_osal_thread_t *thread)
{
}

/* TODO(ameba): implement — nn_osal/thread.h */
int nn_osal_thread_name_set(nn_osal_thread_t *thread, const char *name)
{
    return -ENOTSUP;
}
