/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/time.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/time.h>

/* TODO(ameba): implement — nn_osal/time.h */
int64_t nn_osal_uptime_ms(void)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/time.h */
uint32_t nn_osal_uptime_ms_32(void)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/time.h */
uint32_t nn_osal_sleep_ms(uint32_t ms)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/time.h */
void nn_osal_busy_wait_us(uint32_t us)
{
}
