/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/uart.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/uart.h>

/* TODO(ameba): implement — nn_osal/uart.h */
nn_osal_uart_t * nn_osal_uart_get(const char *logical_name)
{
    return NULL;
}

/* TODO(ameba): implement — nn_osal/uart.h */
int nn_osal_uart_register(const char *logical_name, nn_osal_uart_t *uart)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/uart.h */
bool nn_osal_uart_is_ready(const nn_osal_uart_t *uart)
{
    return false;
}

/* TODO(ameba): implement — nn_osal/uart.h */
void nn_osal_uart_irq_callback_set(nn_osal_uart_t *uart, nn_osal_uart_irq_cb_t cb, void *user)
{
}

/* TODO(ameba): implement — nn_osal/uart.h */
void nn_osal_uart_irq_rx_enable(nn_osal_uart_t *uart)
{
}

/* TODO(ameba): implement — nn_osal/uart.h */
void nn_osal_uart_irq_rx_disable(nn_osal_uart_t *uart)
{
}

/* TODO(ameba): implement — nn_osal/uart.h */
bool nn_osal_uart_irq_is_pending(nn_osal_uart_t *uart)
{
    return false;
}

/* TODO(ameba): implement — nn_osal/uart.h */
int nn_osal_uart_irq_update(nn_osal_uart_t *uart)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/uart.h */
bool nn_osal_uart_irq_rx_ready(nn_osal_uart_t *uart)
{
    return false;
}

/* TODO(ameba): implement — nn_osal/uart.h */
int nn_osal_uart_fifo_read(nn_osal_uart_t *uart, uint8_t *buf, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/uart.h */
void nn_osal_uart_poll_out(nn_osal_uart_t *uart, uint8_t byte)
{
}
