/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/watchdog.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/watchdog.h>

/* TODO(ameba): implement — nn_osal/watchdog.h */
int nn_osal_task_wdt_init(uint32_t hardware_period_ms, nn_osal_wdt_panic_cb_t panic_cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/watchdog.h */
nn_osal_wdt_channel_t nn_osal_task_wdt_add(uint32_t timeout_ms)
{
    return 0;
}

/* TODO(ameba): implement — nn_osal/watchdog.h */
int nn_osal_task_wdt_feed(nn_osal_wdt_channel_t channel)
{
    return -ENOTSUP;
}
