/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_osal/work.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_osal/work.h>

/* TODO(ameba): implement — nn_osal/work.h */
void nn_osal_work_init(nn_osal_work_t *work, nn_osal_work_handler_t handler)
{
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_submit(nn_osal_work_t *work)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_submit_to_queue(nn_osal_work_queue_t *q, nn_osal_work_t *work)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_busy(const nn_osal_work_t *work)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/work.h */
void nn_osal_work_delayable_init(nn_osal_work_delayable_t *dw, nn_osal_work_delayable_handler_t handler)
{
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_schedule(nn_osal_work_delayable_t *dw, uint32_t delay_ms)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_reschedule(nn_osal_work_delayable_t *dw, uint32_t delay_ms)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_cancel_delayable(nn_osal_work_delayable_t *dw)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_osal/work.h */
nn_osal_work_delayable_t * nn_osal_work_delayable_from_work(nn_osal_work_t *w)
{
    return NULL;
}

/* TODO(ameba): implement — nn_osal/work.h */
int nn_osal_work_queue_start(nn_osal_work_queue_t *q, void *stack, size_t stack_size, int prio, const char *name)
{
    return -ENOTSUP;
}
