/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_infer/policy.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_infer/policy.h>

/* TODO(ameba): implement — nn_infer/policy.h */
void nn_infer_policy_set(nn_infer_class_state_t *st, const nn_infer_class_policy_t *cfg)
{
}

/* TODO(ameba): implement — nn_infer/policy.h */
uint16_t nn_infer_policy_feed(nn_infer_class_state_t *st, uint16_t conf_x1000, bool *changed)
{
    return 0;
}
