/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_pal/ble.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_pal/ble.h>

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_init(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_shutdown(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
bool nn_pal_ble_is_ready(void)
{
    return false;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_set_device_name(const char *name)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_uuid_from_str(nn_pal_ble_uuid_t *out, const char *s)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_register_service(nn_pal_ble_service_t *svc)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_notify(nn_pal_ble_conn_t conn, uint16_t chrc_handle, const void *data, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_advertise_start(const nn_pal_ble_adv_params_t *p)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_advertise_stop(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_scan_start(const nn_pal_ble_scan_params_t *params, nn_pal_ble_scan_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_scan_stop(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_conn_cb_register(nn_pal_ble_conn_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_conn_disconnect(nn_pal_ble_conn_t conn)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_connect(const uint8_t addr[6], uint8_t addr_type)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_mtu_exchange(nn_pal_ble_conn_t conn)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_discover(nn_pal_ble_conn_t conn, const nn_pal_ble_uuid_t *svc_uuid, nn_pal_ble_remote_chrc_t *chrcs, size_t chrc_count, nn_pal_ble_disco_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_read(nn_pal_ble_conn_t conn, uint16_t handle, nn_pal_ble_gatt_read_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_write(nn_pal_ble_conn_t conn, uint16_t handle, const void *data, size_t len, nn_pal_ble_gatt_write_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_gatt_subscribe(nn_pal_ble_conn_t conn, uint16_t value_handle, uint16_t ccc_handle, nn_pal_ble_gatt_notify_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/ble.h */
int nn_pal_ble_set_pairing_mode(nn_pal_ble_pairing_mode_t m)
{
    return -ENOTSUP;
}
