/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_pal/dfu.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_pal/dfu.h>

/* TODO(ameba): implement — nn_pal/dfu.h */
nn_pal_dfu_ctx_t * nn_pal_dfu_ctx_alloc(void)
{
    return NULL;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
void nn_pal_dfu_ctx_free(nn_pal_dfu_ctx_t *ctx)
{
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_begin(nn_pal_dfu_ctx_t *ctx, size_t expected_size)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_write(nn_pal_dfu_ctx_t *ctx, const uint8_t *buf, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_finalise(nn_pal_dfu_ctx_t *ctx)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_request_upgrade(bool permanent)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_confirm(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_get_state(nn_pal_dfu_state_t *out)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_erase_secondary(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_slot_read(int slot, uint32_t off, uint8_t *buf, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_slot1_erase(uint32_t off, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
int nn_pal_dfu_slot1_write(uint32_t off, const uint8_t *buf, size_t len)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/dfu.h */
uint32_t nn_pal_dfu_slot1_size(void)
{
    return 0;
}
