/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_pal/log_sink.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_pal/log_sink.h>

/* TODO(ameba): implement — nn_pal/log_sink.h */
int nn_pal_log_sink_register(nn_pal_log_sink_cb_t cb, void *user, uint8_t min_level)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/log_sink.h */
int nn_pal_log_sink_unregister(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/log_sink.h */
void nn_pal_log_sink_panic(void)
{
}

/* TODO(ameba): implement — nn_pal/log_sink.h */
void nn_pal_log_thread_suspend(void)
{
}

/* TODO(ameba): implement — nn_pal/log_sink.h */
void nn_pal_log_thread_resume(void)
{
}
