/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_pal/mdns.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_pal/mdns.h>

/* TODO(ameba): implement — nn_pal/mdns.h */
int nn_pal_mdns_set_hostname(const char *host)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/mdns.h */
int nn_pal_mdns_advertise(const char *service_type, uint16_t port, const nn_pal_mdns_txt_t *txt, size_t txt_count, nn_pal_mdns_service_t *out_handle)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/mdns.h */
int nn_pal_mdns_unpublish(nn_pal_mdns_service_t handle)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/mdns.h */
int nn_pal_mdns_init(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/mdns.h */
void nn_pal_mdns_shutdown(void)
{
}
