/* SPDX-License-Identifier: Apache-2.0 */
/*
 * nn_pal/openthread.h — ameba backend, NOT YET IMPLEMENTED.
 *
 * Generated by scripts/gen_notsup_backend.py.  Every function here is
 * defined and returns -ENOTSUP (or the nearest equivalent its return
 * type allows) so that the seam is COMPLETE while none of it works.
 *
 * That distinction is the point.  A missing symbol is a link error
 * indistinguishable from a typo; an explicit -ENOTSUP is a decision a
 * caller can test and a reader can check.  It also lets T0 measure
 * something real from the first day of the port instead of drowning in
 * undefined references.
 *
 * Replace these as the real backend lands, and DELETE the stub when you
 * do -- a stub left beside a real implementation is how a platform ends
 * up quietly answering -ENOTSUP in production.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <nn_pal/openthread.h>

/* TODO(ameba): implement — nn_pal/openthread.h */
int nn_pal_ot_init(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
nn_pal_ot_instance_t nn_pal_ot_instance(void)
{
    return 0;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
void nn_pal_ot_mutex_lock(void)
{
}

/* TODO(ameba): implement — nn_pal/openthread.h */
void nn_pal_ot_mutex_unlock(void)
{
}

/* TODO(ameba): implement — nn_pal/openthread.h */
int nn_pal_ot_iface_start(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
int nn_pal_ot_iface_stop(void)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
bool nn_pal_ot_is_commissioned(void)
{
    return false;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
int nn_pal_ot_state_cb_register(nn_pal_ot_state_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
int nn_pal_ot_state_cb_unregister(nn_pal_ot_state_cb_t cb, void *user)
{
    return -ENOTSUP;
}

/* TODO(ameba): implement — nn_pal/openthread.h */
uint32_t nn_pal_ot_iface_scope_id(void)
{
    return 0;
}
