#!/usr/bin/env python3
"""Generate an explicitly-unimplemented backend for a new platform.

    scripts/gen_notsup_backend.py <backend-name> [--seam nn_osal] [--force]

Writes modules/libs/<seam>/src/<backend>/<header>.c for every seam header,
with every declared function DEFINED and returning -ENOTSUP (or the nearest
equivalent for its return type).

Why generate rather than hand-write: the contract is that a backend which
cannot do something still defines the function and returns -ENOTSUP, because a
missing symbol is indistinguishable from a typo while an explicit -ENOTSUP is
a decision a reader can check.  Holding to that by hand across 154 functions
means 154 chances to mistype a signature; generated stubs match the header by
construction, and T0 then measures something real from day one of a port.

These are a STARTING POINT, not an answer.  Every one of them is a promise not
yet kept, so each carries a TODO naming its seam.  As real code replaces a
stub, delete the stub -- do not leave both.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SEAMS = {
    "nn_osal": "modules/libs/nn_osal",
    "nn_pal": "modules/libs/nn_pal",
    "nn_infer": "modules/libs/nn_infer",
}

BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)
LINE_COMMENT = re.compile(r"//[^\n]*")
DIRECTIVE = re.compile(r"^[ \t]*#(?:[^\n\\]|\\\r?\n)*", re.M)
# A trailing __attribute__((...)) is legal on a DECLARATION and not on a
# DEFINITION, so it has to come off before we emit a body -- otherwise gcc
# rejects "attributes should be specified before the declarator".
# One level of nesting, because the payload is routinely a call-like form:
# __attribute__((format(printf, 3, 4))).  A lazy ".*?\)\)" stops at the first
# "))", which there is inside "4)))", and leaves a stray paren behind.
ATTRIBUTE = re.compile(r"__attribute__\s*\(\((?:[^()]|\([^()]*\))*\)\)", re.S)
# capture the whole declaration: everything up to the name, the name, and the
# parenthesised parameter list.
DECL = re.compile(
    r"(?P<ret>(?:[A-Za-z_][A-Za-z_0-9]*\s+|\*\s*)+?)"
    r"(?P<name>nn_(?:osal|pal|infer)_[a-z0-9_]+)\s*"
    r"\((?P<args>[^;]*)\)\s*$",
    re.S,
)


def clean(text: str) -> str:
    return DIRECTIVE.sub("", LINE_COMMENT.sub("", BLOCK_COMMENT.sub("", text)))


def body_for(ret: str) -> str:
    """What an unimplemented function of this return type should give back."""
    r = " ".join(ret.split())
    if r == "void":
        return None                       # no return statement at all
    if "*" in r:
        return "    return NULL;"
    if r in ("int", "int32_t", "long", "ssize_t"):
        return "    return -ENOTSUP;"
    if r in ("bool",):
        return "    return false;"
    # Unsigned and enum returns cannot carry -ENOTSUP.  Zero is the least
    # surprising value, and the TODO above it is what stops that being read as
    # a real answer.
    return "    return 0;"


def declarations(header: pathlib.Path):
    out = []
    for chunk in clean(header.read_text(errors="replace")).split(";"):
        if chunk.lstrip().startswith("typedef") or "{" in chunk:
            continue
        attrs = " ".join(ATTRIBUTE.findall(chunk))
        chunk = ATTRIBUTE.sub("", chunk)
        m = DECL.search(chunk.strip())
        if not m:
            continue
        name = m.group("name")
        if name.endswith("_t"):
            continue
        ret = " ".join(m.group("ret").split())
        args = " ".join(m.group("args").split()) or "void"
        # A declaration whose return type parsed as nothing is a parser miss,
        # not a void function; refuse rather than emit a wrong signature.
        if not ret:
            sys.exit(f"gen_notsup: could not parse the return type of {name} "
                     f"in {header.name}; fix the parser rather than guessing")
        out.append((ret, name, args, "noreturn" in attrs))
    return out


def render(seam: str, header: pathlib.Path, backend: str, decls) -> str:
    lines = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/*",
        f" * {seam}/{header.name} — {backend} backend, NOT YET IMPLEMENTED.",
        " *",
        " * Generated by scripts/gen_notsup_backend.py.  Every function here is",
        " * defined and returns -ENOTSUP (or the nearest equivalent its return",
        " * type allows) so that the seam is COMPLETE while none of it works.",
        " *",
        " * That distinction is the point.  A missing symbol is a link error",
        " * indistinguishable from a typo; an explicit -ENOTSUP is a decision a",
        " * caller can test and a reader can check.  It also lets T0 measure",
        " * something real from the first day of the port instead of drowning in",
        " * undefined references.",
        " *",
        " * Replace these as the real backend lands, and DELETE the stub when you",
        " * do -- a stub left beside a real implementation is how a platform ends",
        " * up quietly answering -ENOTSUP in production.",
        " */",
        "",
        "#include <errno.h>",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#include <{seam}/{header.name}>",
        "",
    ]
    for ret, name, args, noreturn in decls:
        lines.append(f"/* TODO({backend}): implement — {seam}/{header.name} */")
        lines.append(f"{ret} {name}({args})")
        lines.append("{")
        if noreturn:
            # The header promises this never returns, so the stub must not
            # either -- returning from a noreturn function is undefined, and
            # the caller after it is unreachable code the compiler removed.
            lines.append("    /* declared noreturn: a stub must not return */")
            lines.append("    for (;;) { }")
        else:
            body = body_for(ret)
            if body:
                lines.append(body)
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("backend")
    ap.add_argument("--seam", action="append", choices=sorted(SEAMS))
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing stub files")
    args = ap.parse_args()

    seams = args.seam or sorted(SEAMS)
    total = 0
    for seam in seams:
        incdir = ROOT / SEAMS[seam] / "include" / seam
        outdir = ROOT / SEAMS[seam] / "src" / args.backend
        outdir.mkdir(parents=True, exist_ok=True)
        for header in sorted(incdir.glob("*.h")):
            decls = declarations(header)
            if not decls:
                continue
            out = outdir / (header.stem + ".c")
            if out.exists() and not args.force:
                print(f"  skip {out.relative_to(ROOT)} (exists; --force to replace)")
                continue
            out.write_text(render(seam, header, args.backend, decls))
            print(f"  wrote {out.relative_to(ROOT)} ({len(decls)} functions)")
            total += len(decls)
    print(f"gen_notsup: {total} functions stubbed for '{args.backend}'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
