#!/usr/bin/env python3
"""Generate the T0 symbol census from the seam headers.

The census is GENERATED, not hand-written, and that is the whole point.  A
hand-maintained list of 182 references stops covering the function someone
adds next week, and T0 then reports "complete" about a seam it is no longer
checking -- which is the exact failure mode the tier is supposed to prevent.
So the list comes from the headers every time, and cts/runner/t0_census.sh
fails if the committed file has drifted from them.

Usage:
    gen_t0_symbols.py --check            # committed file matches the headers?
    gen_t0_symbols.py --write            # regenerate it
    gen_t0_symbols.py --list             # one symbol per line, for tooling
"""
import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "cts" / "runner" / "t0_symbols.c"

# seam -> public header directory.  A new seam is added here, not in the
# generated file.
SEAMS = {
    "nn_osal": "modules/libs/nn_osal/include/nn_osal",
    "nn_pal": "modules/libs/nn_pal/include/nn_pal",
    "nn_infer": "modules/libs/nn_infer/include/nn_infer",
}

BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)
LINE_COMMENT = re.compile(r"//[^\n]*")
# A preprocessor directive, including backslash continuations.  These must be
# removed LINE BY LINE, not by discarding any ';'-chunk that contains one: a
# macro has no semicolon of its own, so it shares a chunk with whatever real
# declaration follows it, and throwing the chunk away silently dropped
# nn_osal_thread_create, nn_osal_log_emit and nn_pal_dfu_slot_read from the
# census.  A census that under-covers is worse than none, because T0 then
# reports "complete" about symbols it never looked at.
DIRECTIVE = re.compile(r"^[ \t]*#(?:[^\n\\]|\\\r?\n)*", re.M)
# a declared seam function: a name in the seam's namespace, immediately
# followed by '('.  Names ending _t are types and callback typedefs.
DECL = re.compile(r"\b(nn_(?:osal|pal|infer)_[a-z0-9_]+)\s*\(")


def strip_comments(text: str) -> str:
    """Comments and preprocessor directives gone; declarations intact."""
    text = BLOCK_COMMENT.sub("", text)
    text = LINE_COMMENT.sub("", text)
    return DIRECTIVE.sub("", text)


def declarations(header: pathlib.Path) -> list[str]:
    """Function names DECLARED (not defined, not typedef'd) in one header."""
    text = strip_comments(header.read_text(errors="replace"))
    found = []
    # Declarations end at a semicolon.  Splitting on ';' is enough once
    # comments are gone, and it keeps each candidate small enough to reason
    # about with the tests below.
    for chunk in text.split(";"):
        if chunk.lstrip().startswith("typedef"):
            continue          # callback typedefs are types, not symbols
        if "{" in chunk:
            continue          # a definition (static inline), not a link symbol
        for name in DECL.findall(chunk):
            if name.endswith("_t"):
                continue      # a type, not a function
            # A call inside a static inline body would look like a
            # declaration; the '{' test above already excluded those, so
            # anything left is genuinely declared here.
            found.append(name)
    return found


def census() -> list[tuple[str, str, str]]:
    """(seam, header basename, symbol), sorted and de-duplicated."""
    rows: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for seam, rel in SEAMS.items():
        d = ROOT / rel
        if not d.is_dir():
            sys.exit(f"gen_t0_symbols: no such header dir: {rel}")
        for header in sorted(d.glob("*.h")):
            for name in declarations(header):
                if name in seen:
                    continue
                seen.add(name)
                rows.append((seam, header.name, name))
    if not rows:
        sys.exit("gen_t0_symbols: found no declarations at all -- "
                 "the parser is broken, and an empty census would PASS")
    return rows


def render(rows) -> str:
    try:
        rev = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        rev = "unknown"

    groups: dict[tuple[str, str], list[str]] = {}
    for seam, header, name in rows:
        groups.setdefault((seam, header), []).append(name)

    def guard(seam: str, header: str) -> str:
        return "NN_CTS_SKIP_" + (seam + "_" + header).upper().replace(".", "_")

    lines = [
        "/* GENERATED by cts/runner/gen_t0_symbols.py -- do not edit.",
        " *",
        " * T0, the symbol census.  Taking the address of every function",
        " * declared in every seam header means a backend that is missing one",
        " * fails to link HERE, on a host, instead of on the board.",
        " *",
        " * What a green T0 does NOT mean: that any of this works.  The BlueZ",
        " * backend had every symbol in this table and deadlocked on its first",
        " * write.  T0 says the backend is COMPLETE; T1 upward say whether it",
        " * behaves.  Treating a green census as evidence about behaviour is",
        " * the mistake this comment exists to prevent.",
        " *",
        " * A backend that cannot implement a call should still DEFINE it and",
        " * return -ENOTSUP.  A missing symbol is indistinguishable from a",
        " * typo; an explicit -ENOTSUP is a decision someone can read.",
        " *",
        " * Only functions with LINK symbols are here.  The seam headers also",
        " * provide static inline helpers and macros (byteorder, libc shims,",
        " * some accessors); those come from the header itself, so a backend",
        " * cannot fail to supply them and a census cannot check them.  They",
        " * need behavioural tests in T1 instead -- do not read this file as",
        " * the whole API surface.",
        " *",
        " * Per-header groups are skippable, because the seam surface is not",
        " * uniform: on posix, uart/watchdog/work have no backend at all.  A",
        " * platform declares its skips in cts/platforms/<name>.yaml and the",
        " * census PRINTS them, so a narrowed census is a visible decision",
        " * rather than a quietly smaller number.",
        " *",
        f" * {len(rows)} symbols in {len(groups)} groups, generated at {rev}.",
        " */",
        "",
        "#include <stddef.h>",
        "",
        "struct nn_cts_symbol {",
        "    const char *seam;",
        "    const char *header;",
        "    const char *name;",
        "    void       *addr;",
        "};",
        "",
        "/* A function pointer is not portably castable to void*, so route it",
        " * through a uniform function type and an integer of pointer width;",
        " * every toolchain in this project accepts that. */",
        "#define NN_CTS_SYM(seam, header, fn) \\",
        "    { seam, header, #fn, (void *)(size_t)(void (*)(void))(fn) }",
        "",
    ]

    for (seam, header) in groups:
        g = guard(seam, header)
        lines += [f"#ifndef {g}", f"#include <{seam}/{header}>", f"#endif"]
    lines += ["", "const struct nn_cts_symbol nn_cts_symbols[] = {"]
    for (seam, header), names in groups.items():
        g = guard(seam, header)
        lines.append(f"#ifndef {g}")
        for name in names:
            lines.append(f'    NN_CTS_SYM("{seam}", "{header}", {name}),')
        lines.append(f"#endif")
    lines += [
        "};",
        "",
        "const size_t nn_cts_symbol_count =",
        "    sizeof(nn_cts_symbols) / sizeof(nn_cts_symbols[0]);",
        "",
        "/* Every group this build was compiled WITHOUT, so the runner can say",
        " * what it did not look at.  A census that silently shrinks is the",
        " * failure this list exists to prevent. */",
        "const char *const nn_cts_skipped[] = {",
    ]
    for (seam, header) in groups:
        g = guard(seam, header)
        lines += [f"#ifdef {g}", f'    "{seam}/{header}",', "#endif"]
    lines += [
        "    NULL,",
        "};",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    g.add_argument("--list", action="store_true")
    args = ap.parse_args()

    rows = census()

    if args.list:
        for _, _, name in rows:
            print(name)
        return 0

    text = render(rows)

    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"gen_t0_symbols: wrote {OUT.relative_to(ROOT)} "
              f"({len(rows)} symbols)")
        return 0

    # --check: compare everything except the generated-at line, which moves
    # with every commit and would make this fail for no reason.
    def norm(s: str) -> str:
        return "\n".join(l for l in s.splitlines()
                         if not l.startswith(" * ") or "generated at" not in l)

    if not OUT.exists():
        print(f"gen_t0_symbols: {OUT.relative_to(ROOT)} is missing; "
              f"run --write", file=sys.stderr)
        return 1
    if norm(OUT.read_text()) != norm(text):
        print("gen_t0_symbols: the census is STALE -- a seam header declares "
              "something the committed file does not cover.", file=sys.stderr)
        print("gen_t0_symbols: run cts/runner/gen_t0_symbols.py --write",
              file=sys.stderr)
        return 1
    print(f"gen_t0_symbols: census is current ({len(rows)} symbols)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
