/* GENERATED by cts/runner/gen_t0_symbols.py -- do not edit.
 *
 * T0, the symbol census.  Taking the address of every function
 * declared in every seam header means a backend that is missing one
 * fails to link HERE, on a host, instead of on the board.
 *
 * What a green T0 does NOT mean: that any of this works.  The BlueZ
 * backend had every symbol in this table and deadlocked on its first
 * write.  T0 says the backend is COMPLETE; T1 upward say whether it
 * behaves.  Treating a green census as evidence about behaviour is
 * the mistake this comment exists to prevent.
 *
 * A backend that cannot implement a call should still DEFINE it and
 * return -ENOTSUP.  A missing symbol is indistinguishable from a
 * typo; an explicit -ENOTSUP is a decision someone can read.
 *
 * Only functions with LINK symbols are here.  The seam headers also
 * provide static inline helpers and macros (byteorder, libc shims,
 * some accessors); those come from the header itself, so a backend
 * cannot fail to supply them and a census cannot check them.  They
 * need behavioural tests in T1 instead -- do not read this file as
 * the whole API surface.
 *
 * Per-header groups are skippable, because the seam surface is not
 * uniform: on posix, uart/watchdog/work have no backend at all.  A
 * platform declares its skips in cts/platforms/<name>.yaml and the
 * census PRINTS them, so a narrowed census is a visible decision
 * rather than a quietly smaller number.
 *
 * 154 symbols in 21 groups, generated at 28dbfba.
 */

#include <stddef.h>

struct nn_cts_symbol {
    const char *seam;
    const char *header;
    const char *name;
    void       *addr;
};

/* A function pointer is not portably castable to void*, so route it
 * through a uniform function type and an integer of pointer width;
 * every toolchain in this project accepts that. */
#define NN_CTS_SYM(seam, header, fn) \
    { seam, header, #fn, (void *)(size_t)(void (*)(void))(fn) }

#ifndef NN_CTS_SKIP_NN_OSAL_BUF_H
#include <nn_osal/buf.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_GPIO_H
#include <nn_osal/gpio.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_LOG_H
#include <nn_osal/log.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SHELL_H
#include <nn_osal/shell.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SOCKET_H
#include <nn_osal/socket.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_STORAGE_H
#include <nn_osal/storage.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SYNC_H
#include <nn_osal/sync.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SYSTEM_H
#include <nn_osal/system.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_THREAD_H
#include <nn_osal/thread.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_TIME_H
#include <nn_osal/time.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_UART_H
#include <nn_osal/uart.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_WATCHDOG_H
#include <nn_osal/watchdog.h>
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_WORK_H
#include <nn_osal/work.h>
#endif
#ifndef NN_CTS_SKIP_NN_PAL_BLE_H
#include <nn_pal/ble.h>
#endif
#ifndef NN_CTS_SKIP_NN_PAL_DFU_H
#include <nn_pal/dfu.h>
#endif
#ifndef NN_CTS_SKIP_NN_PAL_LOG_SINK_H
#include <nn_pal/log_sink.h>
#endif
#ifndef NN_CTS_SKIP_NN_PAL_MDNS_H
#include <nn_pal/mdns.h>
#endif
#ifndef NN_CTS_SKIP_NN_PAL_OPENTHREAD_H
#include <nn_pal/openthread.h>
#endif
#ifndef NN_CTS_SKIP_NN_PAL_WIFI_H
#include <nn_pal/wifi.h>
#endif
#ifndef NN_CTS_SKIP_NN_INFER_NN_INFER_H
#include <nn_infer/nn_infer.h>
#endif
#ifndef NN_CTS_SKIP_NN_INFER_POLICY_H
#include <nn_infer/policy.h>
#endif

const struct nn_cts_symbol nn_cts_symbols[] = {
#ifndef NN_CTS_SKIP_NN_OSAL_BUF_H
    NN_CTS_SYM("nn_osal", "buf.h", nn_osal_buf_map),
    NN_CTS_SYM("nn_osal", "buf.h", nn_osal_buf_unmap),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_GPIO_H
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_get),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_register),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_from_raw),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_configure),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_get_logical),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_set_logical),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_toggle),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_port_ready),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_callback_init),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_add_callback),
    NN_CTS_SYM("nn_osal", "gpio.h", nn_osal_gpio_interrupt_configure),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_LOG_H
    NN_CTS_SYM("nn_osal", "log.h", nn_osal_log_emit),
    NN_CTS_SYM("nn_osal", "log.h", nn_osal_log_emit_v),
    NN_CTS_SYM("nn_osal", "log.h", nn_osal_printk),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SHELL_H
    NN_CTS_SYM("nn_osal", "shell.h", nn_osal_shell_print),
    NN_CTS_SYM("nn_osal", "shell.h", nn_osal_shell_error),
    NN_CTS_SYM("nn_osal", "shell.h", nn_osal_shell_warn),
    NN_CTS_SYM("nn_osal", "shell.h", nn_osal_shell_print_v),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SOCKET_H
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_socket),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_close),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_bind),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_connect),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_listen),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_accept),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_send),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_sendto),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_recv),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_recvfrom),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_setsockopt),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_poll),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_inet_pton6),
    NN_CTS_SYM("nn_osal", "socket.h", nn_osal_inet_ntop6),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_STORAGE_H
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_kv_init),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_kv_register),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_kv_load_all),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_kv_save),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_kv_delete),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_ctx_alloc),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_ctx_free),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_begin),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_write),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_finalise),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_request_upgrade),
    NN_CTS_SYM("nn_osal", "storage.h", nn_osal_dfu_confirm),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SYNC_H
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_sem_init),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_sem_take),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_sem_give),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_sem_reset),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_sem_count_get),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_mutex_init),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_mutex_lock),
    NN_CTS_SYM("nn_osal", "sync.h", nn_osal_mutex_unlock),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_SYSTEM_H
    NN_CTS_SYM("nn_osal", "system.h", nn_osal_sys_reboot),
    NN_CTS_SYM("nn_osal", "system.h", nn_osal_sys_panic),
    NN_CTS_SYM("nn_osal", "system.h", nn_osal_app_version),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_THREAD_H
    NN_CTS_SYM("nn_osal", "thread.h", nn_osal_thread_create),
    NN_CTS_SYM("nn_osal", "thread.h", nn_osal_thread_yield),
    NN_CTS_SYM("nn_osal", "thread.h", nn_osal_thread_suspend),
    NN_CTS_SYM("nn_osal", "thread.h", nn_osal_thread_resume),
    NN_CTS_SYM("nn_osal", "thread.h", nn_osal_thread_name_set),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_TIME_H
    NN_CTS_SYM("nn_osal", "time.h", nn_osal_uptime_ms),
    NN_CTS_SYM("nn_osal", "time.h", nn_osal_uptime_ms_32),
    NN_CTS_SYM("nn_osal", "time.h", nn_osal_sleep_ms),
    NN_CTS_SYM("nn_osal", "time.h", nn_osal_busy_wait_us),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_UART_H
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_get),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_register),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_is_ready),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_irq_callback_set),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_irq_rx_enable),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_irq_rx_disable),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_irq_is_pending),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_irq_update),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_irq_rx_ready),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_fifo_read),
    NN_CTS_SYM("nn_osal", "uart.h", nn_osal_uart_poll_out),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_WATCHDOG_H
    NN_CTS_SYM("nn_osal", "watchdog.h", nn_osal_task_wdt_init),
    NN_CTS_SYM("nn_osal", "watchdog.h", nn_osal_task_wdt_add),
    NN_CTS_SYM("nn_osal", "watchdog.h", nn_osal_task_wdt_feed),
#endif
#ifndef NN_CTS_SKIP_NN_OSAL_WORK_H
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_init),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_submit),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_submit_to_queue),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_busy),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_delayable_init),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_schedule),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_reschedule),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_cancel_delayable),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_delayable_from_work),
    NN_CTS_SYM("nn_osal", "work.h", nn_osal_work_queue_start),
#endif
#ifndef NN_CTS_SKIP_NN_PAL_BLE_H
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_init),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_shutdown),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_is_ready),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_set_device_name),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_uuid_from_str),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_register_service),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_notify),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_advertise_start),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_advertise_stop),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_scan_start),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_scan_stop),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_conn_cb_register),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_conn_disconnect),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_connect),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_mtu_exchange),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_discover),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_read),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_write),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_gatt_subscribe),
    NN_CTS_SYM("nn_pal", "ble.h", nn_pal_ble_set_pairing_mode),
#endif
#ifndef NN_CTS_SKIP_NN_PAL_DFU_H
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_ctx_alloc),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_ctx_free),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_begin),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_write),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_finalise),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_request_upgrade),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_confirm),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_get_state),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_erase_secondary),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_slot_read),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_slot1_erase),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_slot1_write),
    NN_CTS_SYM("nn_pal", "dfu.h", nn_pal_dfu_slot1_size),
#endif
#ifndef NN_CTS_SKIP_NN_PAL_LOG_SINK_H
    NN_CTS_SYM("nn_pal", "log_sink.h", nn_pal_log_sink_register),
    NN_CTS_SYM("nn_pal", "log_sink.h", nn_pal_log_sink_unregister),
    NN_CTS_SYM("nn_pal", "log_sink.h", nn_pal_log_sink_panic),
    NN_CTS_SYM("nn_pal", "log_sink.h", nn_pal_log_thread_suspend),
    NN_CTS_SYM("nn_pal", "log_sink.h", nn_pal_log_thread_resume),
#endif
#ifndef NN_CTS_SKIP_NN_PAL_MDNS_H
    NN_CTS_SYM("nn_pal", "mdns.h", nn_pal_mdns_set_hostname),
    NN_CTS_SYM("nn_pal", "mdns.h", nn_pal_mdns_advertise),
    NN_CTS_SYM("nn_pal", "mdns.h", nn_pal_mdns_unpublish),
    NN_CTS_SYM("nn_pal", "mdns.h", nn_pal_mdns_init),
    NN_CTS_SYM("nn_pal", "mdns.h", nn_pal_mdns_shutdown),
#endif
#ifndef NN_CTS_SKIP_NN_PAL_OPENTHREAD_H
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_init),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_instance),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_mutex_lock),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_mutex_unlock),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_iface_start),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_iface_stop),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_is_commissioned),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_state_cb_register),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_state_cb_unregister),
    NN_CTS_SYM("nn_pal", "openthread.h", nn_pal_ot_iface_scope_id),
#endif
#ifndef NN_CTS_SKIP_NN_PAL_WIFI_H
    NN_CTS_SYM("nn_pal", "wifi.h", nn_pal_wifi_init),
    NN_CTS_SYM("nn_pal", "wifi.h", nn_pal_wifi_connect),
    NN_CTS_SYM("nn_pal", "wifi.h", nn_pal_wifi_disconnect),
    NN_CTS_SYM("nn_pal", "wifi.h", nn_pal_wifi_get_state),
    NN_CTS_SYM("nn_pal", "wifi.h", nn_pal_wifi_is_connected),
#endif
#ifndef NN_CTS_SKIP_NN_INFER_NN_INFER_H
    NN_CTS_SYM("nn_infer", "nn_infer.h", nn_infer_init),
    NN_CTS_SYM("nn_infer", "nn_infer.h", nn_infer_query_caps),
    NN_CTS_SYM("nn_infer", "nn_infer.h", nn_infer_run),
    NN_CTS_SYM("nn_infer", "nn_infer.h", nn_infer_deinit),
#endif
#ifndef NN_CTS_SKIP_NN_INFER_POLICY_H
    NN_CTS_SYM("nn_infer", "policy.h", nn_infer_policy_set),
    NN_CTS_SYM("nn_infer", "policy.h", nn_infer_policy_feed),
#endif
};

const size_t nn_cts_symbol_count =
    sizeof(nn_cts_symbols) / sizeof(nn_cts_symbols[0]);

/* Every group this build was compiled WITHOUT, so the runner can say
 * what it did not look at.  A census that silently shrinks is the
 * failure this list exists to prevent. */
const char *const nn_cts_skipped[] = {
#ifdef NN_CTS_SKIP_NN_OSAL_BUF_H
    "nn_osal/buf.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_GPIO_H
    "nn_osal/gpio.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_LOG_H
    "nn_osal/log.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_SHELL_H
    "nn_osal/shell.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_SOCKET_H
    "nn_osal/socket.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_STORAGE_H
    "nn_osal/storage.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_SYNC_H
    "nn_osal/sync.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_SYSTEM_H
    "nn_osal/system.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_THREAD_H
    "nn_osal/thread.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_TIME_H
    "nn_osal/time.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_UART_H
    "nn_osal/uart.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_WATCHDOG_H
    "nn_osal/watchdog.h",
#endif
#ifdef NN_CTS_SKIP_NN_OSAL_WORK_H
    "nn_osal/work.h",
#endif
#ifdef NN_CTS_SKIP_NN_PAL_BLE_H
    "nn_pal/ble.h",
#endif
#ifdef NN_CTS_SKIP_NN_PAL_DFU_H
    "nn_pal/dfu.h",
#endif
#ifdef NN_CTS_SKIP_NN_PAL_LOG_SINK_H
    "nn_pal/log_sink.h",
#endif
#ifdef NN_CTS_SKIP_NN_PAL_MDNS_H
    "nn_pal/mdns.h",
#endif
#ifdef NN_CTS_SKIP_NN_PAL_OPENTHREAD_H
    "nn_pal/openthread.h",
#endif
#ifdef NN_CTS_SKIP_NN_PAL_WIFI_H
    "nn_pal/wifi.h",
#endif
#ifdef NN_CTS_SKIP_NN_INFER_NN_INFER_H
    "nn_infer/nn_infer.h",
#endif
#ifdef NN_CTS_SKIP_NN_INFER_POLICY_H
    "nn_infer/policy.h",
#endif
    NULL,
};

